version: "3.8"
services:
    webapp:
        build:
            context: .
        ports:
            - "9090:8080"
    nginx:
        restart: always
        build:
            context: ./nginx-conf
        ports:
            - "9999:80"

            